function DoseGui(dat, figname)

fig_h = figure('Position', [44 332 1014 638], 'Name', figname);
axisopts = fieldnames(dat)';
pos = get(fig_h, 'position');



x_h = uicontrol(fig_h, ....
    'Style',  'popupmenu',...
    'String', [{'x'} axisopts],...
    'Position', [pos(3)*0.1 pos(4)*0.8 pos(3)*0.15 pos(4)*0.1],...
    'Callback', '');

y_h = uicontrol(fig_h, ....
    'Style',  'popupmenu',...
    'String', [{'y'} axisopts],...
    'Position', [pos(3)*0.1 pos(4)*0.7 pos(3)*0.15 pos(4)*0.1],...
    'Callback', '');



uicontrol(fig_h,...
    'Style', 'pushbutton',...
    'Position', [pos(3)*0.1 pos(4)*0.4 pos(3)*0.15 pos(4)*0.15],...
    'String',   'plot \w err', ...
    'Callback', @call_ploterr);


uicontrol(fig_h,...
    'Style', 'pushbutton',...
    'Position', [pos(3)*0.1 pos(4)*0.2 pos(3)*0.15 pos(4)*0.15],...
    'String',   'scatter', ...
    'Callback', @call_scXY);


    function call_ploterr(~, ~)
        delete(gca)
        ploterr(setConstraints(dat), x_h.String{x_h.Value}, y_h.String{y_h.Value})
        set(gca, 'Position', [0.35 0.15 0.6 0.7]);
        crossl;

    end

    function call_scXY(~, ~)
        delete(gca)
        scXY(setConstraints(dat), x_h.String{x_h.Value}, y_h.String{y_h.Value})
        set(gca, 'Position', [0.35 0.15 0.6 0.7]);
        crossl;
    end

end

